// flow-typed signature: 44996779d2add184de05b256e8c18f6f
// flow-typed version: <<STUB>>/babel-eslint_v4.x.x/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-eslint/eslint-tester' {
  declare module.exports: any;
}

declare module 'babel-eslint/test/babel-eslint' {
  declare module.exports: any;
}

declare module 'babel-eslint/test/non-regression' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-eslint/eslint-tester.js' {
  declare module.exports: $Exports<'babel-eslint/eslint-tester'>;
}
declare module 'babel-eslint/index' {
  declare module.exports: $Exports<'babel-eslint'>;
}
declare module 'babel-eslint/index.js' {
  declare module.exports: $Exports<'babel-eslint'>;
}
declare module 'babel-eslint/test/babel-eslint.js' {
  declare module.exports: $Exports<'babel-eslint/test/babel-eslint'>;
}
declare module 'babel-eslint/test/non-regression.js' {
  declare module.exports: $Exports<'babel-eslint/test/non-regression'>;
}
