// flow-typed signature: dde2c5e77a31cd05e12a323db0fbc60f
// flow-typed version: <<STUB>>/deep-for-each_v^1.0.6/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-for-each'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-for-each' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-for-each/index.umd' {
  declare module.exports: any;
}

declare module 'deep-for-each/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-for-each/index' {
  declare module.exports: $Exports<'deep-for-each'>;
}
declare module 'deep-for-each/index.js' {
  declare module.exports: $Exports<'deep-for-each'>;
}
declare module 'deep-for-each/index.umd.js' {
  declare module.exports: $Exports<'deep-for-each/index.umd'>;
}
declare module 'deep-for-each/test/test.js' {
  declare module.exports: $Exports<'deep-for-each/test/test'>;
}
